@startuml
"サーバ" -> DHCPサーバ: 誰かIPアドレスくれ
"DHCPサーバ" -> サーバ: お前のIPアドレスこれな
"サーバ" -> dnsmasq: わしPXEブートなんやけど誰か助けて
"dnsmasq" -> サーバ: 起動イメージはここ( matchbox )にあるで
"サーバ" -> matchbox: dnsmasqさんに言われてきました。起動イメージください
"matchbox" -> サーバ: まずiPXEで起動しなおしてきてね
"サーバ" -> matchbox: iPXEで起動したで。わしのMACアドレスはこれなんじゃが次どうすれば
matchbox -> サーバ: 君のMACアドレスの登録は... 無いなー。まぁ初回セットアップだろうしNETBOOT.XYZに転送するわ
"サーバ" -> NETBOOT.XYZ: いろいろディスクレスブートできるブートメニューください
NETBOOT.XYZ -> サーバ: ブートメニューこれな。メニューから選択したら起動に必要なカーネルイメージ、パラメータ、initramfsの情報渡すからね
@enduml
