@startuml
"サーバ" -> DHCPサーバ: 誰かIPアドレスくれ
"DHCPサーバ" -> サーバ: お前のIPアドレスこれな
"サーバ" -> dnsmasq: わしPXEブートなんやけど誰か助けて
"dnsmasq" -> サーバ: 起動イメージはここ( matchbox )にあるで
"サーバ" -> matchbox: dnsmasqさんに言われて来ました、起動イメージください
"matchbox" -> サーバ: まずiPXEで起動しなおして来てね
"サーバ" -> matchbox: iPXEで起動したで。わしのMACアドレスはこれじゃが次どうすれば
matchbox -> サーバ: 君はCoreOSな、起動イメージとカーネルパラメータとinitramfsはこれやで
"サーバ" -> matchbox: カーネルパラメータ内にignitionファイルのパスが書かれてた。このignitionファイルくれ
matchbox -> サーバ: これな
"サーバ" -> サーバ: まずストレージをマウントするか
"サーバ" -> サーバ: それから必要なファイルを設置して
"サーバ" -> サーバ: dockerサービスを起動して
"サーバ" -> サーバ: kindのセットアップスクリプトを走らせるか
@enduml
